title: Recipes Are Just Guidelines
tagline: Blueprints for tasty recipes
baseurl: /
url: http://www.recipesarejustguidelines.com
email: contact@recipesarejustguidelines.com
paginate: 10
timezone: America/Chicago
excerpt_separator: <!--more-->
highlighter: null
permalink: /:title/
collections:
  my_tags:
    output: true
    permalink: /tag/:name/
exclude:
  - README.md
  - Gemfile
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Amanda"
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tag
  
# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

repository: RecipesAreJustGuidelines/RecipesAreJustGuidelines.github.io